apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: computervision
    app.kubernetes.io/instance: nginx-argocd-application
  name: computervision-argocd
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computervision
  template:
    metadata:
      labels:
        app: computervision
    spec:
      containers:
        - image: 'localhost:5000/computervision:2.0'
          name: computervision-container
          ports:
            - containerPort: 8024
              name: http-web-svc
          resources:
            limits:
              nvidia.com/gpu: "1"  # Assuming you have 1 GPU, adjust as per your setup
      restartPolicy: Always  # Restart policy for the container
