
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: knowledge-assistance
    app.kubernetes.io/instance: nginx-argocd-application
  name: knowledge-assistance-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knowledge-assistance
  template:
    metadata:
      labels:
        app: knowledge-assistance
    spec:
      containers:
      - name: knowledge-assistance
        image: 10.10.45.1:5000/ai-apis_knowledge_assistance:latest  # Use the correct image path here
        ports:
        - containerPort: 1406
        volumeMounts:
        - mountPath: /knowledge_assistance/db
          name: db-path
        - mountPath: /knowledge_assistance/api_utils
          name: api-utils-path
      volumes:
      - name: db-path
        hostPath:
          path: /mnt/SDD1/ai-apis/knowledge_assistance/db
      - name: api-utils-path
        hostPath:
          path: /mnt/SDD1/ai-apis/api_utils
      restartPolicy: Always
