apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      app: computervision
      app.kubernetes.io/instance: nginx-argocd-application
  name: computervision-deployment
  namespace: app
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: computervision
  template:
    metadata:
      labels:
        app: computervision
    spec:
      containers:
        - name: computervision-container
          image: 'localhost:5000/computervision:2.0'
          ports:
            - containerPort: 8024
      restartPolicy: Always  # Restart policy for the container