apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nginx-argocd-application
  name: computervision-service-argocd
  namespace: app
spec:
  ports:
    - nodePort: 30086
      port: 8024
      targetPort: http-web-svc
  selector:
    app: computervision
  type: LoadBalancer

