apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nginx-argocd-application
  name: nginx-service-argocd
  namespace: app
spec:
  ports:
    - nodePort: 30086
      port: 8066
      targetPort: http-web-svc
  selector:
    app: nginx
  type: LoadBalancer
