apiVersion: v1
kind: Service
metadata:
  labels:
      app.kubernetes.io/instance: nginx-argocd-application
  name: computervision-service
  namespace: app
spec:
  selector:
    app: computervision
  ports:
    - protocol: TCP
      port: 8024       # The port that the service will expose
      targetPort: 8024  # The port on the container to direct traffic to
  type: LoadBalancer  # Change to NodePort if running locally or without a cloud provider