apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nginx-argocd-application
  name: transcription-service
  namespace: app
spec:
  selector:
    app: transcription
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 50051
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nginx-argocd-application
  name: speech-synthesis-service
  namespace: app
spec:
  selector:
    app: speech-synthesis
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 1407
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nginx-argocd-application
  name: digital-literacy-service
  namespace: app
spec:
  selector:
    app: digital-literacy
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 1405
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nginx-argocd-application
  name: knowledge-assistance-service
  namespace: app
spec:
  selector:
    app: knowledge-assistance
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 1406
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nginx-argocd-application
  name: omiefe-ai-service
  namespace: app
spec:
  selector:
    app: omiefe-ai
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 1404
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: multilang-translation
    app.kubernetes.io/instance: nginx-argocd-application
  name: multilang-translation-service
  namespace: app
spec:
  selector:
    app: multilang-translation
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 1401
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: srt-translation
    app.kubernetes.io/instance: nginx-argocd-application
  name: srt-translation-service
  namespace: app
spec:
  selector:
    app: srt-translation
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 1402
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: srt-to-audio
    app.kubernetes.io/instance: nginx-argocd-application
  name: srt-to-audio-service
  namespace: app
spec:
  selector:
    app: srt-to-audio
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 1403
  type: LoadBalancer

